name: country_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^8.0.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.8.0+1
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  gap: ^3.0.1
  dartz: ^0.10.1
  flutter_animate_on_scroll: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
